services:
  # New container "ex_06_db" for mysql database
  ex_06_db:
    image: mysql:latest # Set image to latest from mysql
    restart: always # Docker will always attempt to restart the container if it exits
    environment:
      MYSQL_DATABASE: nimzar_db # Setup database
      MYSQL_ROOT_PASSWORD: root # Set the password
      MYSQL_USER: nimzar # Set database user name
      MYSQL_PASSWORD: nimzar_pws # Set database password
    ports:
      - "3306:3306" # Set the ports
    volumes:
      - C:\data\mysql-c:/var/lib/mysql # Set path for storing database data, linked to the path data is stored by default

  ex_06_adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

# Volume creation
volumes:
  db-data:  # Create volume "db-data" for persistant storage

